#!/bin/bash


sudo yum install openssl openssl-devel
sudo yum groupinstall "Development Tools"

sudo yum install git-core
git clone git://github.com/joyent/node.git

cd node
./configure
make

sudo make install
node -v

sudo yum install curl

sudo su
PATH=$PATH:/home/ec2-user/node
export PATH
curl http://npmjs.org/install.sh | sh
exit